services:
  quicknotes:
    build:
      context: ./app
    image: quicknotes:lab6
    ports:
      - "8080:8080"
    volumes:
      - quicknotes-data:/data
    healthcheck:
      test: ["CMD", "/quicknotes", "healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    environment:
      ADDR: ":8080"
      DATA_PATH: /data/notes.json
      SEED_PATH: /data/seed.json
    restart: unless-stopped

volumes:
  quicknotes-data: